### ISSUE TITLE
Integração E-mail/QR Code

### ISSUE THREAD

**Issue by maczord** [os-salvadores/fillmyseat#10]
Professor
---
Botão para compartilhar evento com os alunos por e-mail

Requisitos
---
O compartilhamento por e-mail pode ser feito em dois momentos:
1. quando o QR Code é gerado
2. quando as configurações do evento são acessadas

**Comment by gasscoelho** [comment]
### **Desenvolvimento**
- Compartilhar QR Code com os alunos.
_[Nível de prioridade para a aplicação: **ALTA** | Nível de conhecimento Técnico: **BAIXA**]_

**Comment by gasscoelho** [comment]
> ## Professor
> Botão para compartilhar evento com os alunos por e-mail
> 
> ## Requisitos
> O compartilhamento por e-mail pode ser feito em dois momentos:
> 
> 1. quando o QR Code é gerado
> 2. quando as configurações do evento são acessadas

Como deverá ser feito esse compartilhamento de QR Code via e-mail visto que o aluno precisará do próprio telefone para realizar a leitura?

**Comment by maczord** [comment]
> > ## Professor
> > Botão para compartilhar evento com os alunos por e-mail
> > ## Requisitos
> > O compartilhamento por e-mail pode ser feito em dois momentos:
> > 
> > 1. quando o QR Code é gerado
> > 2. quando as configurações do evento são acessadas
> 
> Como deverá ser feito esse compartilhamento de QR Code via e-mail visto que o aluno precisará do próprio telefone para realizar a leitura?

Pensando nessa funcionalidade agora, acho que só funciona para eventos em casos de Shows e Festas, onde o participante pode imprimir o QR Code para ser escaneado na hora. Ou retiramos ou damos essa possibilidade de o aluno levar impresso.

Por mim pode remover essa função
