### ISSUE TITLE
Integração/Firebase

### ISSUE THREAD

**Issue by maczord** [os-salvadores/fillmyseat#11]
Utilização do Firebase para a integração dos dados em tempo real.

**Comment by gasscoelho** [comment]
### **Desenvolvimento**
- Autenticação de usuário
_[Nível de prioridade para a aplicação: **ALTO** | Conhecimento Técnico: **MÉDIO**]_
- Inserção dos dados na nuvem (firebase), incluindo a relação entre usuários e eventos. 
_[Nível de prioridade para a aplicação: **ALTO** | Conhecimento Técnico: **BAIXO**]_
