### ISSUE TITLE
Leitura de QR Code

### ISSUE THREAD

**Issue by victorwerneck** [os-salvadores/fillmyseat#13]
### Aluno
Se inscreve no evento e faz o Check-in através do QR Code.

### Requisito
Abrir câmera para fazer leitura do QR Code e gerar confirmação de acesso

**Comment by gasscoelho** [comment]
### **Desenvolvimento**
- Possibilitar a leitura do QR Code a partir da própria aplicação.
_[Nível de prioridade para a aplicação: **ALTA** | Nível de conhecimento Técnico: **BAIXA**]_
