### ISSUE TITLE
Configuração de evento

### ISSUE THREAD

**Issue by victorwerneck** [os-salvadores/fillmyseat#14]
### Professor
Professor criou o evento e depois precisa cancelar o mesmo

### Requisitos
Ter permissão de professor no App e já ter um evento criado previamente

**Comment by maczord** [comment]
![Prof_Detalhes do Evento – Cancelar Evento](https://user-images.githubusercontent.com/51265688/59203977-0f439580-8b76-11e9-80e9-3998e7b0234d.png)
![Prof_Detalhes do Evento – QR Code](https://user-images.githubusercontent.com/51265688/59203978-0f439580-8b76-11e9-9fc7-c8ddc744ffe0.png)
![Prof_Detalhes do Evento](https://user-images.githubusercontent.com/51265688/59203979-0f439580-8b76-11e9-8142-e2b63b382be2.png)
![Prof_Home - Com Eventos](https://user-images.githubusercontent.com/51265688/59203980-0fdc2c00-8b76-11e9-8183-edff155ce40c.png)
