### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by maczord** [os-salvadores/fillmyseat#3]

**Comment by maczord** [comment]
![Login](https://user-images.githubusercontent.com/51265688/58813135-8a96cb80-85f9-11e9-82ac-5a73f958767b.png)

**Comment by gasscoelho** [comment]
### **Desenvolvimento**
- Validar a Autenticação do usuário. Caso o e-mail ou a senha estejam errado, é necessário apresentar uma mensagem de error ao usuário. **_[DONE]_**
_[Nível de prioridade para a aplicação: **ALTO** | Nível de conhecimento Técnico: **MÉDIO**]_
- Carregar as informações do usuário logado no Shared Preferences, deste modo, evitaria o carregamento das informações do usuário na tela de Home Events. **_[DONE]_**
_[Nível de prioridade para a aplicação: **MÉDIO** | Nível de conhecimento Técnico: **ALTO** ]_
- Verificar a possibilidade de inserir um animação de "loading" ao clicar no botão "Entrar". **_[FOR NOW USING ANOTHER SIMPLE SOLUTION]_**
 _[Nível de prioridade para a aplicação: **BAIXA** | Nível de conhecimento Técnico: **BAIXO**]_ 
- Verificar a possibilidade de redefinir senha através de um TOKEN via e-mail, neste caso seria enviado ao e-mail do usuário um código (token) para que ele insira na tela de redefinição de senha (nova tela). Caso o código inserido pelo usuário esteja correto, será apresentado os campos necessários para a alteração da senha. 
[Nível de prioridade para a aplicação: **BAIXA** | Conhecimento Técnico: **BAIXO**]

**Comment by gasscoelho** [comment]
Sugestão para alteração do Layout da tela de login:

![WhatsApp Image 2019-06-09 at 23 55 07](https://user-images.githubusercontent.com/33602013/59174829-6bcc9380-8b29-11e9-8a78-84918f74308d.jpeg)
