### ISSUE TITLE
Novo Evento

### ISSUE THREAD

**Issue by maczord** [os-salvadores/fillmyseat#5]
Professor
---
Como professor
Quero criar novos eventos
Para inserir meus alunos ou compartilhar o QR Code com aqueles que não tem matrícula

Requisitos
---
Somente uma conta com perfil de professor pode criar eventos

**Comment by maczord** [comment]
![Criar Evento – 2](https://user-images.githubusercontent.com/51265688/58813169-97b3ba80-85f9-11e9-9ebc-6a247fe77e37.png)
![Criar Evento – 3](https://user-images.githubusercontent.com/51265688/58813172-97b3ba80-85f9-11e9-9792-c7ac9d4966d5.png)
![Criar Evento](https://user-images.githubusercontent.com/51265688/58813173-984c5100-85f9-11e9-8294-d44ecd0f37eb.png)

**Comment by maczord** [comment]
Temos que corrigir o bug dos espaços de input. Quando o usuário aperta "enter" o input quebra uma linha em vez de concluir ou seguir para o próximo input

**Comment by maczord** [comment]
Design
---
Duração do evento em horas
Localização (input de texto)

**Comment by maczord** [comment]
Desenvolvimento
---
Validar os dados configurados

**Comment by gasscoelho** [comment]
> Temos que corrigir o bug dos espaços de input. Quando o usuário aperta "enter" o input quebra uma linha em vez de concluir ou seguir para o próximo input

Bug corrigido.

**Comment by maczord** [comment]
Vou fazer os ajustes de Design agora

**Comment by maczord** [comment]
> Vou fazer os ajustes de Design agora

Baseado nas discussões, acredito que essa seja a melhor solução para essa tela.

@gasscoelho é muito difícil implementar desse jeito? Para o input de horas, pensei numa rolagem dupla em duas colunas, uma para as Horas e outra para os Minutos
![Criar Evento – 2](https://user-images.githubusercontent.com/51265688/59198204-8888bb80-8b69-11e9-95da-9d7c4eb34b80.png)
