### ISSUE TITLE
Gerar QR Code

### ISSUE THREAD

**Issue by maczord** [os-salvadores/fillmyseat#9]
Professor
---
Como Professor
Preciso gerar um QR Code do evento
Para compartilhar com os alunos

Requisitos
---
Para gerar um QR Code, o evento já deve ter sido criado.
O QR Code só pode ser gerado se faltar pelo menos 1h para começar o evento.

**Comment by victorwerneck** [comment]
Ciente

Em sáb, 8 de jun de 2019 14:42, maczord <notifications@github.com> escreveu:

**Comment by gasscoelho** [comment]
Desenvolvimento
- Gerar QR Code automaticamente para cada evento. Para isso será necessário a utilização de um identificador único, como por exemplo, código (uid) do usuário + código do evento + data do evento com duração de início. 
Exemplo: 0sVtvQgziYf2DYZTBjSXxVLlDng2 + LPE010008 + 15062019 + 9
_[Nível de prioridade para a aplicação: **ALTA** | Nível de conhecimento Técnico: **BAIXA**]_
